<?php

use App\Apartment;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ApartmentsSeeder extends Seeder
{
    public function run()
    {
        $apartments = [
            [
                'title' => 'Appartamento a Roma',
                'description' => 'Appartamento',
                'isVisible' => 1,
                'room_numbers' => 2,
                'bed_numbers' => 3,
                'bathroom_numbers' => 2,
                'square_meters' => 201,
                'cover' => 'cover',
                'price_per_night' => 69,
                'country' => 'Italia',
                'region' => 'Lazio',
                'province' => 'Roma',
                'streetAddress' => 'Largo dei Lombardi 23, 00187 Roma',
                'longitude' => 12.477944,
                'latitude' => 41.9059015,
                'slug' => 'Appartamento-a-roma-5',
                'user_id' => 1,
            ],
            [
                'title' => 'Appartamento a Milano',
                'description' => 'Appartamento',
                'isVisible' => 1,
                'room_numbers' => 3,
                'bed_numbers' => 1,
                'bathroom_numbers' => 1,
                'square_meters' => 63,
                'cover' => 'cover',
                'price_per_night' => 24,
                'country' => 'Italia',
                'region' => 'Lombardia',
                'province' => 'Milano',
                'streetAddress' => 'Galleria del Corso, 4 20122 Milano',
                'longitude' => 9.195207,
                'latitude' => 45.464821,
                'slug' => 'Appartamento-a-milano-5',
                'user_id' => 1,
            ],
            [
                'title' => 'Appartamento a Torino',
                'description' => 'Appartamento',
                'isVisible' => 1,
                'room_numbers' => 6,
                'bed_numbers' => 3,
                'bathroom_numbers' => 2,
                'square_meters' => 49,
                'cover' => 'cover',
                'price_per_night' => 17,
                'country' => 'Italia',
                'region' => 'Piemonte',
                'province' => 'Torino',
                'streetAddress' => 'Via del Carmine 3, 10122 Torino',
                'longitude' => 7.676150,
                'latitude' => 45.075320,
                'slug' => 'Appartamento-a-torino-5',
                'user_id' => 1,
            ],
            [
                'title' => 'Appartamento a Palermo',
                'description' => 'Appartamento',
                'isVisible' => 1,
                'room_numbers' => 3,
                'bed_numbers' => 4,
                'bathroom_numbers' => 1,
                'square_meters' => 27,
                'cover' => 'cover',
                'price_per_night' => 24,
                'country' => 'Italia',
                'region' => 'Sicilia',
                'province' => 'Palermo',
                'streetAddress' => 'Via Marchese di Villabianca 120, 90143 Palermo',
                'longitude' => 13.348660,
                'latitude' => 38.139350,
                'slug' => 'Appartamento-a-palermo',
                'user_id' => 1,
            ],
            [
                'title' => 'Appartamento a Bari',
                'description' => 'Appartamento',
                'isVisible' => 1,
                'room_numbers' => 2,
                'bed_numbers' => 1,
                'bathroom_numbers' => 3,
                'square_meters' => 53,
                'cover' => 'cover',
                'price_per_night' => 45,
                'country' => 'Italia',
                'region' => 'Puglia',
                'province' => 'Bari',
                'streetAddress' => 'Via G. Devitofrancesco 4/A, 70100 Bari',
                'longitude' => 16.866410,
                'latitude' => 41.115080,
                'slug' => 'Appartamento-a-bari',
                'user_id' => 1,
            ],
            [
                'title' => 'Appartamento a Bologna',
                'description' => 'Appartamento',
                'isVisible' => 1,
                'room_numbers' => 5,
                'bed_numbers' => 1,
                'bathroom_numbers' => 3,
                'square_meters' => 65,
                'cover' => 'cover',
                'price_per_night' => 24,
                'country' => 'Italia',
                'region' => 'Emilia Romagna',
                'province' => 'Bologna',
                'streetAddress' => 'Via dell industria 35, 40138 Bologna',
                'longitude' => 11.404570,
                'latitude' => 44.504700,
                'slug' => 'Appartamento-a-bologna',
                'user_id' => 1,
            ],
            [
                'title' => 'Appartamento a Milano',
                'description' => 'Appartamento',
                'isVisible' => 1,
                'room_numbers' => 3,
                'bed_numbers' => 2,
                'bathroom_numbers' => 1,
                'square_meters' => 6,
                'cover' => 'cover',
                'price_per_night' => 24,
                'country' => 'Italia',
                'region' => 'Lombardia',
                'province' => 'Milano',
                'streetAddress' => 'Via Alessandro Manzoni 6, 20121 Milano',
                'longitude' => 9.190630,
                'latitude' => 45.467890,
                'slug' => 'Appartamento-a-milano-2',
                'user_id' => 1,
            ],
            [
                'title' => 'Appartamento a Firenze',
                'description' => 'Appartamento',
                'isVisible' => 1,
                'room_numbers' => 3,
                'bed_numbers' => 1,
                'bathroom_numbers' => 1,
                'square_meters' => 63,
                'cover' => 'cover',
                'price_per_night' => 24,
                'country' => 'Italia',
                'region' => 'Toscana',
                'province' => 'Firenze',
                'streetAddress' => 'Via della vigna nuova 5, 50123 Firenze',
                'longitude' => 11.2503164,
                'latitude' => 43.7712735,
                'slug' => 'Appartamento-a-firenze-5',
                'user_id' => 1,
            ],
            [
                'title' => 'Appartamento a Napoli',
                'description' => 'Appartamento',
                'isVisible' => 1,
                'room_numbers' => 3,
                'bed_numbers' => 1,
                'bathroom_numbers' => 4,
                'square_meters' => 254,
                'cover' => 'cover',
                'price_per_night' => 94,
                'country' => 'Italia',
                'region' => 'Campania',
                'province' => 'Napoli',
                'streetAddress' => 'Via Alessandro Scarlatti 3, 80127 Napoli',
                'longitude' => 14.23482,
                'latitude' => 40.844124,
                'slug' => 'Appartamento-a-napoli',
                'user_id' => 1,
            ],
            [
                'title' => 'Appartamento a Roma',
                'description' => 'Appartamento',
                'isVisible' => 1,
                'room_numbers' => 8,
                'bed_numbers' => 6,
                'bathroom_numbers' => 2,
                'square_meters' => 63,
                'cover' => 'cover',
                'price_per_night' => 36,
                'country' => 'Italia',
                'region' => 'Lazio',
                'province' => 'Roma',
                'streetAddress' => 'Via Borgognona 7, 00187 Roma',
                'longitude' => 12.4825287,
                'latitude' => 41.905227,
                'slug' => 'Appartamento-a-roma-6',
                'user_id' => 1,
            ],
            [
                'title' => 'Appartamento a Roma',
                'description' => 'Appartamento',
                'isVisible' => 1,
                'room_numbers' => 5,
                'bed_numbers' => 2,
                'bathroom_numbers' => 1,
                'square_meters' => 123,
                'cover' => 'cover',
                'price_per_night' => 56,
                'country' => 'Italia',
                'region' => 'Lazio',
                'province' => 'Roma',
                'streetAddress' => 'Via Frattina 4, 00187 Roma',
                'longitude' => 12.481354,
                'latitude' => 41.904213,
                'slug' => 'Appartamento-a-roma-7',
                'user_id' => 1,
            ],
        ];

        foreach ($apartments as $apartment) {
            $newApartment = new Apartment();
            $newApartment->fill($apartment);
            $newApartment->save();
          }
    }
}
